### PR TITLE
Split out some models and services into shared repository

### LINKED ISSUE #282: Create new repository and refactor API services into separate module there
We want to be able to reuse the API service code we've written in another application, which requires refactoring it out to its own ngModule and moving it to a different repository. 

The goal of this task is to create the new repo, move the relevant services, and refactor the lab to use the new external dependency.

### PR DESCRIPTION
**Pull request by maurizi**
## Overview

Split out some models and services into [shared repository](https://github.com/azavea/climate-change-components).

A future commit will also move over some components, with an end goal of
being able to share the chart components between two or more Angular applications.

### Demo

N/A. Everything should continue to work as before.

### Notes

Don't use `npm link` to develop in conjunction with changes in `climate-change-components` :disappointed: . See https://github.com/angular/angular-cli/issues/3854.

## Testing Instructions

 * Clone `azavea/climate-change-components` (`hub clone -p azavea/climate-change-components`)
 * Checkout https://github.com/azavea/climate-change-components/pull/3 (`git checkout feature/mvm/init`)
 * Install dependencies for `azavea/climate-change-components` (`yarn`)
 * Build and package the library (`yarn run build:library && npm pack`)
 * In this project, install the package library `cd ../climate-change-lab; npm install ../climate-change-components/climate-change-components-0.0.0.tgz`
 * Running the application should work without any errors (`yarn run serve`)

## Checklist
- [x] `yarn run serve` clean?
- [x] `yarn run build:prod` clean?
- [x] `yarn run lint` clean?

Closes #282

### CODE REVIEW

**Comment by CloudNiner** [comment]
I followed the instructions described in both this and the climate-change-components PRs, and got this error:
```
andrew@acadia:~/src/climate-change-lab$ yarn run serve
yarn run v1.1.0
$ ng serve
The "@angular/compiler-cli" package was not properly installed. Error: Error: Cannot find module '@angular/compiler-cli'
Error: The "@angular/compiler-cli" package was not properly installed. Error: Error: Cannot find module '@angular/compiler-cli'
    at Object.<anonymous> (/usr/local/lib/node_modules/@angular/cli/node_modules/@ngtools/webpack/src/index.js:14:11)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/@angular/cli/tasks/eject.js:10:19)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/@angular/cli/models/webpack-configs/styles.js:6:17)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
when running `yarn run serve` for climate lab. 

No issues with the climate-change-components instructions, that all worked as expected.

**Comment by CloudNiner** [comment]
Was able to successfully build and run the lab after reverting to node 6.11.5 and npm 3.10.10. We should make a separate issue to update the lab to node 8, since that's the source of the failure above.

Looks like the jenkins build fails now due to the missing climate-change-components package. Is there a plan to fix the build in the meantime, or were you planning on just waiting until we address azavea/climate-change-components#4 so we can `yarn install` it?

**Comment by maurizi** [comment]
> Looks like the jenkins build fails now due to the missing climate-change-components package. Is there a plan to fix the build in the meantime, or were you planning on just waiting until we address azavea/climate-change-components#4 so we can yarn install it?

I don't plan on merging this until we have an NPM module for `climate-change-components`

**Comment by maurizi** [comment]
@CloudNiner I've updated this to pull in `climate-change-components` from NPM.

**Pull request merged**
