### PR TITLE
Start visual design

### PR DESCRIPTION
**Pull request by jfrankl**
image

I started bringing in some colors and doing general visual design work. The next big piece is going to be formatting the graph to look more like the wireframes. I will need developer help on that.

### CODE REVIEW

**Comment by CloudNiner** [comment]
+1

**Comment by CloudNiner** [comment]
@jfrankl did you have anything else to add to this? If not, I'll resolve conflicts and merge.

**Comment by jfrankl** [comment]
Nothing else to add. Thanks for offering to resolve conflicts—that would be great.

**Comment by CloudNiner** [comment]
@jfrankl I rebased this, but there's some issues with the city autocomplete dropdown now that it's implemented. I'm not sure what the vision is for the city dropdown/search, could you take another look?

Note that I had to force push after the rebase, so either force pull or delete your local copy of this branch and re-pull.

**Comment by CloudNiner** [comment]
@jfrankl bump

**Comment by CloudNiner** [comment]
Added two small commits to temporarily fixup the city autocomplete input and the chart controls box. Can adjust later as desired.

**Pull request merged**
