### PR TITLE
Feature/routing part two

### PR DESCRIPTION
**Pull request by CloudNiner**
Part two of the routing task, which addresses the remaining items in #18 

I didn't feel like there was quite enough substance here to refactor to a bunch of submodules quite yet  -- I had trouble coming up with clean breaks for where certain things should go. We'll want to address this soon though as we start to add other pages, like the dashboard.

### CODE REVIEW

**Comment by fungjj92** [comment]
Getting error "client:47 ./src/main.browser.ts
Module build failed: Error: Cannot resolve 'file' or 'directory' ../constants"

**Comment by CloudNiner** [comment]
Did you ctrl+c and restart your webpack dev server after pulling this PR? Sometimes the dev server loses file handles when you move files around underneath it.

**Comment by CloudNiner** [comment]
@fungjj92 bump. Did restarting the dev server make this go away? If not, did you `mv src/ccl/constants.ts src/app/`?

**Comment by fungjj92** [comment]
ah duh we have a new root at /app not /ccl

**Comment by fungjj92** [comment]
Thinking about the main template file looking sparse with just component tags is really exciting!!

Re: holding off on component-izing more--> The only other major part is the buttons bar, but that is actively being worked on and would just break stuff unnecessarily now. It may become a little complicated with the autocomplete but we'll cross that bridge.

LGTM

**Pull request merged**
