### PR TITLE
Add text describing chart data source

### LINKED ISSUE #178: Add text area below indicator chart to describe chart sources
For now, this can just contain placeholder text.

screen shot 2017-07-26 at 12 49 18

### PR DESCRIPTION
**Pull request by flibbertigibbet**
## Overview

Add text describing chart sources.

### Demo

image

## Testing Instructions

 * Check text under chart

Closes #178

### CODE REVIEW

**Comment by fungjj92** [comment]
Hm I know that copy was proposed in the issue, but this makes more sense to me:

Derived from the NASA Earth Exchange Global Daily Downscaled Projections (NEX-GDDP) dataset.

**Comment by flibbertigibbet** [comment]
@jcahail have an opinion on the copy?

**Comment by jcahail** [comment]
Looks fine.

**Comment by flibbertigibbet** [comment]
Alright then, updated to just reference NEX.

**Pull request merged**
