### PR TITLE
Update ng bootstrap

### PR DESCRIPTION
**Pull request by fungjj92**
The module was renamed to ngx-bootstrap and the build broke

`vagrant provision`
`cd /opt/climate_change_lab`
`npm start`
Make sure everything bootstrap works, and no errors in log (it did for me)

### CODE REVIEW

**Comment by fungjj92** [comment]
I don't know why this didn't break for me then, but ngx-bootstrap dropdowns broke this time around. everything else seems ok though.

ng2-autocomplete is its own separate repo. are you suggesting renaming to ngx-autocomplete (or something similar)?

**Comment by flibbertigibbet** [comment]
`ng2-autocomplete` source exists in our repo in `src/app/ng2-auto-complete`, so we could rename it if we want to. Or not.

**Comment by fungjj92** [comment]
Hm I'm not getting any console errors. If you think it's appropriate to fix in this PR, can you screenshot the error so I can sleuth it down?

**Comment by flibbertigibbet** [comment]
End of output from `npm start`:

image

**Comment by fungjj92** [comment]
I jumped the gun on this.
I don't understand why I am not seeing the issues you are in my instance D:

**Comment by flibbertigibbet** [comment]
Just repeated, in case it was a transient npm issue:
- `rm -r node_modules`
- `npm install`
- `npm start`

And get mess of red in console, as above.

**Pull request merged**
